import { Country } from '../types';

export const COUNTRIES: Country[] = [
  { code: 'AFG', name: 'Afghanistan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'ALB', name: 'Albania', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'DZA', name: 'Algeria', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'AGO', name: 'Angola', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'ATG', name: 'Antigua and Barbuda', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'ARG', name: 'Argentina', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'ARM', name: 'Armenia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'AUS', name: 'Australia', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'AUT', name: 'Austria', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'AZE', name: 'Azerbaijan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'BHS', name: 'Bahamas', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'BHR', name: 'Bahrain', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'BGD', name: 'Bangladesh', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'BRB', name: 'Barbados', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'BLR', name: 'Belarus', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'BEL', name: 'Belgium', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'BLZ', name: 'Belize', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'BEN', name: 'Benin', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'BTN', name: 'Bhutan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'BOL', name: 'Bolivia', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'BIH', name: 'Bosnia and Herzegovina', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'BWA', name: 'Botswana', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'BRA', name: 'Brazil', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'BRN', name: 'Brunei Darussalam', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'BGR', name: 'Bulgaria', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'BFA', name: 'Burkina Faso', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'BDI', name: 'Burundi', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'KHM', name: 'Cambodia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'CMR', name: 'Cameroon', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'CAN', name: 'Canada', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'CPV', name: 'Cape Verde', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'CAF', name: 'Central African Republic', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'TCD', name: 'Chad', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'CHL', name: 'Chile', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'CHN', name: 'China', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'COL', name: 'Colombia', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'COM', name: 'Comoros', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'COG', name: 'Congo', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'COD', name: 'Democratic Republic of the Congo', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'CRI', name: 'Costa Rica', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'CIV', name: "Côte d'Ivoire", region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'HRV', name: 'Croatia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'CUB', name: 'Cuba', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'CYP', name: 'Cyprus', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'CZE', name: 'Czech Republic', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'DNK', name: 'Denmark', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'DJI', name: 'Djibouti', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'DMA', name: 'Dominica', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'DOM', name: 'Dominican Republic', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'ECU', name: 'Ecuador', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'EGY', name: 'Egypt', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SLV', name: 'El Salvador', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'GNQ', name: 'Equatorial Guinea', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'ERI', name: 'Eritrea', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'EST', name: 'Estonia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'ETH', name: 'Ethiopia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'FJI', name: 'Fiji', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'FIN', name: 'Finland', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'FRA', name: 'France', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'GAB', name: 'Gabon', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'GMB', name: 'Gambia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'GEO', name: 'Georgia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'DEU', name: 'Germany', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'GHA', name: 'Ghana', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'GRC', name: 'Greece', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'GRD', name: 'Grenada', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'GTM', name: 'Guatemala', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'GIN', name: 'Guinea', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'GNB', name: 'Guinea-Bissau', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'GUY', name: 'Guyana', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'HTI', name: 'Haiti', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'HND', name: 'Honduras', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'HUN', name: 'Hungary', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'ISL', name: 'Iceland', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'IND', name: 'India', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'IDN', name: 'Indonesia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'IRN', name: 'Iran', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'IRQ', name: 'Iraq', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'IRL', name: 'Ireland', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'ISR', name: 'Israel', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'ITA', name: 'Italy', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'JAM', name: 'Jamaica', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'JPN', name: 'Japan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'JOR', name: 'Jordan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'KAZ', name: 'Kazakhstan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'KEN', name: 'Kenya', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'KIR', name: 'Kiribati', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'PRK', name: 'North Korea', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'KOR', name: 'South Korea', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'KWT', name: 'Kuwait', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'KGZ', name: 'Kyrgyzstan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'LAO', name: 'Laos', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'LVA', name: 'Latvia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'LBN', name: 'Lebanon', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'LSO', name: 'Lesotho', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'LBR', name: 'Liberia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'LBY', name: 'Libya', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },{ code: 'LIE', name: 'Liechtenstein', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'LTU', name: 'Lithuania', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'LUX', name: 'Luxembourg', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'MDG', name: 'Madagascar', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MWI', name: 'Malawi', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MYS', name: 'Malaysia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'MDV', name: 'Maldives', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'MLI', name: 'Mali', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MLT', name: 'Malta', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'MHL', name: 'Marshall Islands', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'MRT', name: 'Mauritania', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MUS', name: 'Mauritius', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MEX', name: 'Mexico', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'FSM', name: 'Micronesia', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'MDA', name: 'Moldova', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'MCO', name: 'Monaco', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'MNG', name: 'Mongolia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'MNE', name: 'Montenegro', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'MAR', name: 'Morocco', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MOZ', name: 'Mozambique', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'MMR', name: 'Myanmar', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'NAM', name: 'Namibia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'NRU', name: 'Nauru', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'NPL', name: 'Nepal', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'NLD', name: 'Netherlands', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'NZL', name: 'New Zealand', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'NIC', name: 'Nicaragua', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'NER', name: 'Niger', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'NGA', name: 'Nigeria', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'NOR', name: 'Norway', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'OMN', name: 'Oman', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'PAK', name: 'Pakistan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'PLW', name: 'Palau', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'PAN', name: 'Panama', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'PNG', name: 'Papua New Guinea', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'PRY', name: 'Paraguay', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'PER', name: 'Peru', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'PHL', name: 'Philippines', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'POL', name: 'Poland', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'PRT', name: 'Portugal', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'QAT', name: 'Qatar', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'ROU', name: 'Romania', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'RUS', name: 'Russian Federation', region: 'Europe/Asia', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'RWA', name: 'Rwanda', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'KNA', name: 'Saint Kitts and Nevis', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'LCA', name: 'Saint Lucia', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'VCT', name: 'Saint Vincent and the Grenadines', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'WSM', name: 'Samoa', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'SMR', name: 'San Marino', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'STP', name: 'Sao Tome and Principe', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SAU', name: 'Saudi Arabia', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'SEN', name: 'Senegal', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SRB', name: 'Serbia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'SYC', name: 'Seychelles', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SLE', name: 'Sierra Leone', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SGP', name: 'Singapore', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'SVK', name: 'Slovakia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'SVN', name: 'Slovenia', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'SLB', name: 'Solomon Islands', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'SOM', name: 'Somalia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'ZAF', name: 'South Africa', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SSD', name: 'South Sudan', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'ESP', name: 'Spain', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'LKA', name: 'Sri Lanka', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'SDN', name: 'Sudan', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SUR', name: 'Suriname', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'SWZ', name: 'Eswatini', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'SWE', name: 'Sweden', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'CHE', name: 'Switzerland', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'SYR', name: 'Syrian Arab Republic', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'TJK', name: 'Tajikistan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'TZA', name: 'Tanzania', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'THA', name: 'Thailand', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'TLS', name: 'Timor-Leste', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'TGO', name: 'Togo', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'TON', name: 'Tonga', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'TTO', name: 'Trinidad and Tobago', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'TUN', name: 'Tunisia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'TUR', name: 'Turkey', region: 'Europe/Asia', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'TKM', name: 'Turkmenistan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'TUV', name: 'Tuvalu', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'UGA', name: 'Uganda', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'UKR', name: 'Ukraine', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'ARE', name: 'United Arab Emirates', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'GBR', name: 'United Kingdom', region: 'Europe', parentLocationCode: 'EUR', parentLocation: 'Europe' },
  { code: 'USA', name: 'United States of America', region: 'North America', parentLocationCode: 'NAM', parentLocation: 'North America' },
  { code: 'URY', name: 'Uruguay', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'UZB', name: 'Uzbekistan', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'VUT', name: 'Vanuatu', region: 'Oceania', parentLocationCode: 'OCE', parentLocation: 'Oceania' },
  { code: 'VEN', name: 'Venezuela', region: 'South America', parentLocationCode: 'SAM', parentLocation: 'South America' },
  { code: 'VNM', name: 'Viet Nam', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'YEM', name: 'Yemen', region: 'Asia', parentLocationCode: 'ASI', parentLocation: 'Asia' },
  { code: 'ZMB', name: 'Zambia', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' },
  { code: 'ZWE', name: 'Zimbabwe', region: 'Africa', parentLocationCode: 'AFR', parentLocation: 'Africa' }
];







